name: Depdency Check

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  Snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Analyze
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
